import type { KeywordCategory } from "@/features/analysis/lib/types";

interface CatalogEntry {
  phrase: string;
  category: KeywordCategory;
  aliases?: string[];
}

export const keywordCatalog: CatalogEntry[] = [
  { phrase: "react", category: "technical_skill", aliases: ["reactjs"] },
  { phrase: "next.js", category: "technical_skill", aliases: ["nextjs"] },
  { phrase: "vue", category: "technical_skill", aliases: ["vue.js", "vuejs"] },
  { phrase: "angular", category: "technical_skill", aliases: ["angularjs"] },
  { phrase: "redux toolkit", category: "technical_skill", aliases: ["redux", "rtk"] },
  { phrase: "node.js", category: "technical_skill", aliases: ["nodejs", "node js"] },
  { phrase: "typescript", category: "technical_skill" },
  { phrase: "javascript", category: "technical_skill", aliases: ["js"] },
  { phrase: "html5", category: "technical_skill", aliases: ["html 5"] },
  { phrase: "css", category: "technical_skill", aliases: ["css3"] },
  { phrase: "canvas", category: "technical_skill", aliases: ["canvas api"] },
  { phrase: "python", category: "technical_skill" },
  { phrase: "java", category: "technical_skill" },
  { phrase: "kotlin", category: "technical_skill" },
  { phrase: "scala", category: "technical_skill" },
  { phrase: "go", category: "technical_skill", aliases: ["golang"] },
  { phrase: "sql", category: "technical_skill" },
  { phrase: "postgresql", category: "technical_skill", aliases: ["postgres"] },
  { phrase: "mysql", category: "technical_skill" },
  { phrase: "mongodb", category: "technical_skill" },
  { phrase: "redis", category: "technical_skill" },
  { phrase: "graphql", category: "technical_skill" },
  { phrase: "rest api", category: "technical_skill", aliases: ["rest apis", "apis", "api design"] },
  { phrase: "microservices", category: "technical_skill", aliases: ["microservice architecture"] },
  { phrase: "system design", category: "technical_skill", aliases: ["distributed systems"] },
  { phrase: "oop", category: "technical_skill", aliases: ["object oriented programming"] },
  { phrase: "software design patterns", category: "technical_skill", aliases: ["design patterns"] },
  { phrase: "data analysis", category: "technical_skill", aliases: ["analytics", "analysis"] },
  { phrase: "data visualisation", category: "technical_skill", aliases: ["data visualization"] },
  { phrase: "a/b testing", category: "technical_skill", aliases: ["ab testing", "experimentation"] },
  { phrase: "user research", category: "technical_skill", aliases: ["research interviews"] },
  { phrase: "wireframing", category: "technical_skill", aliases: ["wireframes"] },
  { phrase: "design systems", category: "technical_skill", aliases: ["component systems"] },
  { phrase: "accessibility", category: "technical_skill", aliases: ["a11y"] },
  { phrase: "automation testing", category: "technical_skill", aliases: ["automated testing", "test automation"] },
  { phrase: "manual testing", category: "technical_skill" },
  { phrase: "incident management", category: "technical_skill", aliases: ["incident response"] },
  { phrase: "docker", category: "tool" },
  { phrase: "webpack", category: "tool" },
  { phrase: "vite", category: "tool" },
  { phrase: "npm", category: "tool" },
  { phrase: "pnpm", category: "tool" },
  { phrase: "eslint", category: "tool" },
  { phrase: "karma", category: "tool" },
  { phrase: "storybook", category: "tool" },
  { phrase: "less", category: "tool", aliases: ["less css"] },
  { phrase: "tailwind css", category: "tool", aliases: ["tailwind"] },
  { phrase: "figma", category: "tool" },
  { phrase: "jira", category: "tool" },
  { phrase: "git", category: "tool", aliases: ["git workflows", "github", "gitlab"] },
  { phrase: "ci", category: "tool", aliases: ["ci/cd", "ci pipelines", "ci pipeline", "ci environments", "continuous integration"] },
  { phrase: "linux", category: "tool", aliases: ["linux environments"] },
  { phrase: "macos", category: "tool", aliases: ["mac os", "macos environments"] },
  { phrase: "agile", category: "tool", aliases: ["agile methodologies", "agile development", "scrum", "kanban"] },
  { phrase: "kubernetes", category: "tool" },
  { phrase: "aws", category: "tool", aliases: ["amazon web services", "aws lambda", "lambda"] },
  { phrase: "azure", category: "tool" },
  { phrase: "gcp", category: "tool", aliases: ["google cloud"] },
  { phrase: "prisma", category: "tool" },
  { phrase: "github actions", category: "tool" },
  { phrase: "playwright", category: "tool" },
  { phrase: "jest", category: "tool" },
  { phrase: "cypress", category: "tool" },
  { phrase: "selenium", category: "tool" },
  { phrase: "tableau", category: "tool" },
  { phrase: "power bi", category: "tool" },
  { phrase: "communication", category: "soft_skill", aliases: ["communication skills"] },
  { phrase: "collaboration", category: "soft_skill", aliases: ["cross-functional collaboration", "cross functional collaboration"] },
  { phrase: "leadership", category: "soft_skill" },
  { phrase: "ownership", category: "soft_skill" },
  { phrase: "mentoring", category: "soft_skill" },
  { phrase: "stakeholder management", category: "soft_skill" },
  { phrase: "stakeholders", category: "soft_skill", aliases: ["business stakeholders"] },
  { phrase: "problem solving", category: "soft_skill" },
  { phrase: "teamwork", category: "soft_skill" },
  { phrase: "prioritisation", category: "soft_skill", aliases: ["prioritization"] },
  { phrase: "customer empathy", category: "soft_skill", aliases: ["customer focus"] },
  { phrase: "bachelor's degree", category: "qualification", aliases: ["bachelors degree", "bs degree"] },
  { phrase: "master's degree", category: "qualification", aliases: ["masters degree", "ms degree"] },
  { phrase: "computer science", category: "qualification" },
  { phrase: "equivalent experience", category: "qualification" },
  { phrase: "saas", category: "domain" },
  { phrase: "b2b", category: "domain" },
  { phrase: "product engineering", category: "domain" },
  { phrase: "machine learning", category: "domain", aliases: ["ml"] },
  { phrase: "artificial intelligence", category: "domain", aliases: ["ai"] },
  { phrase: "fintech", category: "domain" },
  { phrase: "healthcare", category: "domain" },
  { phrase: "ecommerce", category: "domain", aliases: ["commerce"] },
  { phrase: "retail", category: "domain" },
  { phrase: "manufacturing", category: "domain" },
  { phrase: "education technology", category: "domain", aliases: ["edtech"] },
  { phrase: "customer support", category: "domain" },
  { phrase: "operations", category: "domain" }
];

export const roleTitlePatterns = [
  "software developer",
  "software engineer",
  "frontend engineer",
  "frontend developer",
  "backend engineer",
  "backend developer",
  "full stack engineer",
  "full stack developer",
  "product engineer",
  "product manager",
  "product designer",
  "ux designer",
  "ui designer",
  "data engineer",
  "data analyst",
  "machine learning engineer",
  "devops engineer",
  "site reliability engineer",
  "qa engineer",
  "quality assurance engineer",
  "support engineer",
  "customer support specialist",
  "engineering manager"
] as const;

export const seniorityPatterns = [
  "intern",
  "junior",
  "associate",
  "mid-level",
  "mid level",
  "senior",
  "staff",
  "lead",
  "principal",
  "manager",
  "head"
] as const;
